name: Run end to end tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libmicrohttpd-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Start Server
        run: |
          ${{github.workspace}}/build/x2s &
          # Give the background server 2 seconds to boot before curl hits it
          sleep 2 

      - name: Create Account
        id: create_account
        run: |
          RESPONSE=$(curl -s -f -X POST http://localhost:8080/auth/register -d 'username=alice&password=foobar')

          TOKEN=$(echo "$RESPONSE" | jq -r '.token')
          echo "auth_token=$TOKEN" >> $GITHUB_OUTPUT
      
      - name: Return Token
        run: |
          echo "The token is: ${{ steps.create_account.outputs.auth_token }}"
      
      - name: Login with invalid user
        run: |
          ! curl -s -f -X POST http://localhost:8080/auth/login -d 'username=alice&password=bazquux'
          echo "Unable to login with bad username and password (this is good)"

      - name: Upload object
        id: upload_object
        run: |
          RESPONSE=$(curl -s -f -X POST http://localhost:8080/objects \
          -H "Authorization: Bearer ${{ steps.create_account.outputs.auth_token }}" \
          -H 'X-Filename: hello.txt' \
          -H 'X-Category: documents' \
          -H 'X-Extension: txt' \
          -d 'Hello, World!')

          echo "response=$RESPONSE" >> $GITHUB_OUTPUT
      
      - name: List owned objects
        run: |
          RESPONSE=$(curl -H 'Authorization: Bearer ${{ steps.create_account.outputs.auth_token }}' \
          -X GET "http://localhost:8080/objects")

          echo "Owned objects: $RESPONSE"

          EXPECTED_ID=$(echo '${{ steps.upload_object.outputs.response }}' | jq -r '.id')

          if ! echo "$RESPONSE" | jq --arg id "$EXPECTED_ID" '.objects[] | select(.id == $id)' | grep -q "$EXPECTED_ID"; then
              echo "Error: Uploaded object not found in owned objects."
              exit 1
          fi

      - name: Access object with good auth
        run: |
          ID=$(echo '${{ steps.upload_object.outputs.response }}' | jq -r '.id')
          RESPONSE=$(curl -s -f -X GET "http://localhost:8080/objects/$ID" \
          -H "Authorization: Bearer ${{ steps.create_account.outputs.auth_token }}")

          echo "Accessed object: $RESPONSE"

          if [[ "$RESPONSE" == "Hello, World!" ]]; then
              echo "Successfully accessed the object with good auth."
          else
              echo "Error: Unable to access the object with good auth."
              exit 1
          fi

      - name: Access object with bad auth
        run: |
          ID=$(echo '${{ steps.upload_object.outputs.response }}' | jq -r '.id')
          ! curl -s -f -X GET "http://localhost:8080/objects/$ID"
          echo "Unable to access object (this is good)."

      - name: Log out
        run: |
          curl -s -f -X POST http://localhost:8080/auth/logout \
          -H "Authorization: Bearer ${{ steps.create_account.outputs.auth_token }}"
      
      - name: Access file with expired token
        run: |
          ID=$(echo '${{ steps.upload_object.outputs.response }}' | jq -r '.id')
          ! curl -s -f -X GET "http://localhost:8080/objects/$ID" \
          -H "Authorization: Bearer ${{ steps.create_account.outputs.auth_token }}"
          echo "Unable to access object (this is good)."
      
      - name: Stop Server
        run: |
          pkill x2s || true